name: Go Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Reference your GitHub secret here

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install dependencies
        run: go mod download

      - name: Build the project
        run: go build ./...

      - name: Run tests
        run: go test ./...

      - name: Run Automerge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Reference again if needed in specific steps
        run: |
          ~/automerge -v=1 -setRemoteForCI
